### ISSUE TITLE
Server started/error?!?

### ISSUE THREAD

**Issue by ZockerBoysHD** [mgerb/ServerStatus#17]
I have done all, what you said but if i start the server, it says this:
https://hastebin.com/pinayibaga.rb
What does it mean? I am not getting any messages on my discord for this services i added

**Comment by mgerb** [comment]
If it’s not working you either have something wrong in your config, or you didn’t set up your bot account correctly. I won’t be able to help you out much more without any other information.

**Comment by ZockerBoysHD** [comment]
IT's all set up properly.
I don't have any information either. No errors in console. nothing. just not working.
My Config file: https://hastebin.com/suloqoxojo.json

**Comment by mgerb** [comment]
First of all you have a few things off in your config:

- roles to notify needs to be in the format of `<@&123123>`
- remove the http from your url's (only dns or ip address)

I tested your servers in my bot and it's working just fine, so that makes me think that you configured your discord bot wrong, and or didn't get the correct bot token.

Check to see when you run the bot if the bot shows up online in your discord server. If so, run the command `ServerStatus`.

**Comment by ZockerBoysHD** [comment]
how do i get the role id?

**Comment by ZockerBoysHD** [comment]
It doesn't shows up as a "Client" on my discord server.

**Comment by ZockerBoysHD** [comment]
https://hastebin.com/gicegawafa.json my config.   What do i need, the token from General information or from Bot?

**Comment by ZockerBoysHD** [comment]
ohhh... i forgot to invite the bot. Thank you very much, sir.!
